name: Semantic Release

on:
  push:
    branches:
      - main
      - homolog

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permite fazer push na branch
      pull-requests: write # Permite criar pull requests (opcional)
      issues: write # Permite criar issues (opcional)
    environment:
      name: Semver

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Baixa todo o histórico de commits (necessário para o semantic-release)
          persist-credentials: false # Não persiste as credenciais do repositório

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.15" # Use a versão do Node.js que seu projeto requer

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.6 # Use a versão do pnpm que seu projeto requer

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            - "@semantic-release/exec"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
